#!/bin/bash

###############################################################################
# Coturn STUN/TURN Server Setup Script
# Enables NAT traversal for WebRTC calls
#
# Usage: ./scripts/setup-coturn.sh
###############################################################################

set -e

echo "🚀 Installing and configuring Coturn STUN/TURN server..."

# Detect OS
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    DISTRO=$(lsb_release -si)
    echo "📦 Detected Linux: $DISTRO"

    if [[ "$DISTRO" == "Ubuntu" || "$DISTRO" == "Debian" ]]; then
        echo "📥 Installing coturn..."
        sudo apt-get update
        sudo apt-get install -y coturn
    elif [[ "$DISTRO" == "CentOS" || "$DISTRO" == "RedHat" ]]; then
        echo "📥 Installing coturn..."
        sudo yum install -y coturn
    fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "📦 Detected macOS"
    echo "📥 Installing coturn via Homebrew..."
    brew install coturn
fi

# Get environment variables
EXTERNAL_IP=${EXTERNAL_IP:-$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 || echo "127.0.0.1")}
REALM=${REALM:-$(hostname -f)}
USERNAME=${USERNAME:-turnuser}
PASSWORD=${PASSWORD:-$(openssl rand -base64 32)}
SECRET=${SECRET:-$(openssl rand -base64 32)}

echo ""
echo "⚙️  Coturn Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "External IP: $EXTERNAL_IP"
echo "Realm: $REALM"
echo "Username: $USERNAME"
echo "Password: $PASSWORD"
echo "Secret: $SECRET"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Create Coturn config directory if it doesn't exist
CONFIG_DIR="/etc/coturn"
if [[ ! -d "$CONFIG_DIR" ]]; then
    sudo mkdir -p "$CONFIG_DIR"
fi

# Backup existing config
if [[ -f "$CONFIG_DIR/turnserver.conf" ]]; then
    echo "💾 Backing up existing turnserver.conf..."
    sudo cp "$CONFIG_DIR/turnserver.conf" "$CONFIG_DIR/turnserver.conf.backup"
fi

# Create new Coturn configuration
CONFIG_FILE="$CONFIG_DIR/turnserver.conf"

echo "📝 Writing configuration to $CONFIG_FILE..."

sudo tee "$CONFIG_FILE" > /dev/null << EOF
# Coturn TURN server configuration
# Generated by LifeSync setup script

# Network configuration
listening-port=3478
alt-listening-port=3479
listening-ip=0.0.0.0
external-ip=$EXTERNAL_IP
relay-ip=$EXTERNAL_IP
min-bps=0
bps-capacity=0

# TURN protocol
fingerprint
mobility
keep-address-family

# Authentication
realm=$REALM
server-name=$REALM
user=$USERNAME:$PASSWORD
secret=$SECRET
userdb=/var/lib/coturn/turnuserdb.conf

# Performance
max-bps=0
total-quota=0
bps-capacity=0
max-allocate-lifetime=3600
channel-lifetime=600
permission-lifetime=300
stale-nonce=600

# Logging
log-file=/var/log/coturn/turnserver.log
simple-log
new-log-timestamp
PIDs-file=/var/run/coturn/turnserver.pid

# Security
no-multicast-peers
deny-peers-by-ip={127.0.0.1,::1}
no-tcp
no-udp-relay
no-dtls
no-tls

# WebRTC specific
cli-password=$SECRET
EOF

# Create userdb file
USERDB_FILE="/var/lib/coturn/turnuserdb.conf"
echo "📝 Creating user database at $USERDB_FILE..."

if [[ ! -d "/var/lib/coturn" ]]; then
    sudo mkdir -p "/var/lib/coturn"
fi

sudo tee "$USERDB_FILE" > /dev/null << EOF
# Coturn user database
# Format: username:password
$USERNAME:$PASSWORD
EOF

# Set permissions
sudo chmod 640 "$CONFIG_FILE"
sudo chmod 640 "$USERDB_FILE"
sudo chown turnserver:turnserver "$USERDB_FILE" 2>/dev/null || true

# Create log directory
if [[ ! -d "/var/log/coturn" ]]; then
    sudo mkdir -p "/var/log/coturn"
    sudo chown turnserver:turnserver "/var/log/coturn" 2>/dev/null || true
fi

# Create PID directory
if [[ ! -d "/var/run/coturn" ]]; then
    sudo mkdir -p "/var/run/coturn"
    sudo chown turnserver:turnserver "/var/run/coturn" 2>/dev/null || true
fi

# Start Coturn service
echo "🚀 Starting Coturn service..."
if command -v systemctl &> /dev/null; then
    sudo systemctl enable coturn
    sudo systemctl restart coturn
    echo "✅ Coturn started and enabled"
else
    sudo service coturn restart
    echo "✅ Coturn restarted"
fi

# Verify it's running
echo "🔍 Verifying Coturn is running..."
if sudo systemctl is-active --quiet coturn 2>/dev/null || sudo service coturn status | grep -q "running"; then
    echo "✅ Coturn is running"
else
    echo "⚠️  Coturn may not be running. Check logs:"
    sudo tail -20 /var/log/coturn/turnserver.log
fi

# Test STUN connectivity
echo ""
echo "🧪 Testing STUN connectivity..."
echo "Try connecting to: stun:$EXTERNAL_IP:3478"
echo "Or: turn:$USERNAME:$PASSWORD@$EXTERNAL_IP:3478?transport=udp"

# Save config to environment file for reference
ENV_FILE=".env.coturn"
cat > "$ENV_FILE" << EOF
# Coturn configuration (generated by setup-coturn.sh)
COTURN_EXTERNAL_IP=$EXTERNAL_IP
COTURN_REALM=$REALM
COTURN_USERNAME=$USERNAME
COTURN_PASSWORD=$PASSWORD
COTURN_SECRET=$SECRET
COTURN_STUN_SERVER=stun:$EXTERNAL_IP:3478
COTURN_TURN_SERVER=turn:$USERNAME:$PASSWORD@$EXTERNAL_IP:3478?transport=udp
EOF

echo ""
echo "✅ Coturn setup complete!"
echo "📝 Configuration saved to: .env.coturn"
echo ""
echo "Next steps:"
echo "1. Update your .env file with STUN/TURN server addresses"
echo "2. Add these environment variables to your deployment:"
echo "   STUN_SERVERS=stun:$EXTERNAL_IP:3478"
echo "   TURN_SERVERS=[{\"urls\":[\"turn:$EXTERNAL_IP:3478\"],\"username\":\"$USERNAME\",\"credential\":\"$PASSWORD\"}]"
echo ""
echo "Or copy from .env.coturn and test with:"
echo "   ./scripts/test-coturn.sh"
